package com.example.ui.components

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    SPANISH("es", "Spanish", "Español"),
    FRENCH("fr", "French", "Français"),
    GERMAN("de", "German", "Deutsch"),
    HINDI("hi", "Hindi", "हिन्दी"),
    JAPANESE("ja", "Japanese", "日本語")
}

object LanguageManager {
    var currentLanguage by mutableStateOf(AppLanguage.ENGLISH)

    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "photos" to "Photos",
            "albums" to "Albums",
            "for_you" to "For You",
            "vault" to "Vault",
            "settings" to "Settings",
            "analytics" to "Dashboard",
            "search_hint" to "Search photos, faces, locations...",
            "all_photos" to "All Media",
            "vault_title" to "Private Vault",
            "vault_subtitle" to "AES-256 E2E Encrypted • Zero Cloud Leak",
            "enter_pin" to "Enter 4-Digit Security PIN",
            "unlock_vault" to "Unlock Vault",
            "biometric_unlock" to "Biometric Quick Unlock",
            "sync_status" to "Cloud Sync",
            "battery_priority" to "Battery-Optimized Sync",
            "faces_title" to "Offline Face Recognition",
            "faces_desc" to "100% on-device AI clustering with no telemetry",
            "on_this_day" to "On This Day",
            "motorola_night" to "Motorola Night Vision",
            "voice_hint" to "Tap microphone for voice commands",
            "voice_listening" to "Listening for commands...",
            "voice_commands_avail" to "Try: 'Show Vault', 'Favorites', 'Dark Mode', 'Sync Now', 'Search Portraits'",
            "cloud_backup_now" to "Trigger Encrypted Backup",
            "high_contrast_active" to "High-Contrast Monochrome Mode",
            "ready_for" to "Motorola Ready For Sync",
            "storage_breakdown" to "Storage Telemetry",
            "camera_distribution" to "Camera Sensor Breakdown",
            "engagement_trends" to "Capture Timeline",
            "delete" to "Delete",
            "share" to "Share",
            "vault_move" to "Move to Vault",
            "favorite" to "Favorite",
            "details" to "Details",
            "filters" to "Filters",
            "close" to "Close",
            "unlock_success" to "Vault Unlocked",
            "incorrect_pin" to "Incorrect PIN. Try again.",
            "photos_empty" to "No photos found",
            "scan_faces" to "Re-scan Offline Faces"
        ),
        AppLanguage.SPANISH to mapOf(
            "photos" to "Fotos",
            "albums" to "Álbumes",
            "for_you" to "Para Ti",
            "vault" to "Bóveda",
            "settings" to "Ajustes",
            "analytics" to "Panel",
            "search_hint" to "Buscar fotos, rostros, lugares...",
            "all_photos" to "Todo el contenido",
            "vault_title" to "Bóveda Privada",
            "vault_subtitle" to "Cifrado AES-256 • Cero Fugas",
            "enter_pin" to "Introduce el PIN de 4 dígitos",
            "unlock_vault" to "Desbloquear Bóveda",
            "biometric_unlock" to "Desbloqueo Biométrico",
            "sync_status" to "Sincronización en la Nube",
            "battery_priority" to "Sincronización que ahorra batería",
            "faces_title" to "Reconocimiento Facial Local",
            "faces_desc" to "IA 100% en dispositivo sin telemetría",
            "on_this_day" to "Un Día Como Hoy",
            "motorola_night" to "Visión Nocturna Motorola",
            "voice_hint" to "Pulsa el micrófono para comandos de voz",
            "voice_listening" to "Escuchando comandos...",
            "voice_commands_avail" to "Prueba: 'Abrir Bóveda', 'Favoritos', 'Sincronizar'",
            "cloud_backup_now" to "Iniciar Copia de Seguridad",
            "high_contrast_active" to "Modo Monocromo de Alto Contraste",
            "ready_for" to "Sincronización Motorola Ready For",
            "storage_breakdown" to "Telemetría de Almacenamiento",
            "camera_distribution" to "Desglose de Sensores",
            "engagement_trends" to "Tendencia de Capturas",
            "delete" to "Eliminar",
            "share" to "Compartir",
            "vault_move" to "Mover a Bóveda",
            "favorite" to "Favorito",
            "details" to "Detalles",
            "filters" to "Filtros",
            "close" to "Cerrar",
            "unlock_success" to "Bóveda Desbloqueada",
            "incorrect_pin" to "PIN incorrecto. Reintentar.",
            "photos_empty" to "No hay fotos disponibles",
            "scan_faces" to "Escanear Rostros Locales"
        ),
        AppLanguage.FRENCH to mapOf(
            "photos" to "Photos",
            "albums" to "Albums",
            "for_you" to "Pour Vous",
            "vault" to "Coffre-fort",
            "settings" to "Paramètres",
            "analytics" to "Tableau de Bord",
            "search_hint" to "Rechercher photos, visages...",
            "all_photos" to "Tous les médias",
            "vault_title" to "Coffre Sécurisé",
            "vault_subtitle" to "Cryptage AES-256 de bout en bout",
            "enter_pin" to "Entrez le code PIN à 4 chiffres",
            "unlock_vault" to "Déverrouiller le Coffre",
            "biometric_unlock" to "Déverrouillage Biométrique",
            "sync_status" to "Synchronisation Cloud",
            "battery_priority" to "Économie de Batterie Active",
            "faces_title" to "Reconnaissance Faciale Locale",
            "faces_desc" to "IA 100% sur l'appareil sans données cloud",
            "on_this_day" to "Ce Jour-là",
            "motorola_night" to "Vision Nocturne Motorola",
            "voice_hint" to "Appuyez sur le micro pour la voix",
            "voice_listening" to "À l'écoute...",
            "voice_commands_avail" to "Dites: 'Ouvrir Coffre', 'Favoris', 'Synchroniser'",
            "cloud_backup_now" to "Sauvegarder Maintenant",
            "high_contrast_active" to "Mode Monochrome Haut Contraste",
            "ready_for" to "Synchronisation Motorola Ready For",
            "storage_breakdown" to "Télémétrie Stockage",
            "camera_distribution" to "Répartition des Capteurs",
            "engagement_trends" to "Chronologie des Photos",
            "delete" to "Supprimer",
            "share" to "Partager",
            "vault_move" to "Déplacer au Coffre",
            "favorite" to "Favori",
            "details" to "Détails",
            "filters" to "Filtres",
            "close" to "Fermer",
            "unlock_success" to "Coffre Déverrouillé",
            "incorrect_pin" to "Code PIN erroné.",
            "photos_empty" to "Aucune photo trouvée",
            "scan_faces" to "Scanner les Visages"
        ),
        AppLanguage.GERMAN to mapOf(
            "photos" to "Fotos",
            "albums" to "Alben",
            "for_you" to "Für Dich",
            "vault" to "Tresor",
            "settings" to "Einstellungen",
            "analytics" to "Dashboard",
            "search_hint" to "Fotos, Gesichter, Orte suchen...",
            "all_photos" to "Alle Medien",
            "vault_title" to "Privater Tresor",
            "vault_subtitle" to "AES-256 Ende-zu-Ende verschlüsselt",
            "enter_pin" to "4-stelligen Sicherheits-PIN eingeben",
            "unlock_vault" to "Tresor Öffnen",
            "biometric_unlock" to "Biometrische Entsperrung",
            "sync_status" to "Cloud-Synchronisierung",
            "battery_priority" to "Akkuschonende Synchronisation",
            "faces_title" to "Lokale Gesichtserkennung",
            "faces_desc" to "100% On-Device KI ohne externe Server",
            "on_this_day" to "An diesem Tag",
            "motorola_night" to "Motorola Nachtsicht",
            "voice_hint" to "Mikrofon tippen für Sprachbefehle",
            "voice_listening" to "Höre zu...",
            "voice_commands_avail" to "Versuche: 'Tresor öffnen', 'Favoriten', 'Sync'",
            "cloud_backup_now" to "Verschlüsseltes Backup starten",
            "high_contrast_active" to "Kontrastreicher Schwarz-Weiß-Modus",
            "ready_for" to "Motorola Ready For Sync",
            "storage_breakdown" to "Speicher-Telemetrie",
            "camera_distribution" to "Kamera-Sensoren",
            "engagement_trends" to "Aufnahme-Trends",
            "delete" to "Löschen",
            "share" to "Teilen",
            "vault_move" to "In Tresor verschieben",
            "favorite" to "Favorit",
            "details" to "Details",
            "filters" to "Filter",
            "close" to "Schließen",
            "unlock_success" to "Tresor Entsperrt",
            "incorrect_pin" to "Falscher PIN.",
            "photos_empty" to "Keine Fotos vorhanden",
            "scan_faces" to "Gesichter neu scannen"
        ),
        AppLanguage.HINDI to mapOf(
            "photos" to "तस्वीरें",
            "albums" to "एल्बम",
            "for_you" to "आपके लिए",
            "vault" to "तिजोरी",
            "settings" to "सेटिंग्स",
            "analytics" to "डैशबोर्ड",
            "search_hint" to "तस्वीरें, चेहरे, स्थान खोजें...",
            "all_photos" to "सभी मीडिया",
            "vault_title" to "निजी तिजोरी (Vault)",
            "vault_subtitle" to "AES-256 पूर्ण एन्क्रिप्टेड • शून्य डेटा लीक",
            "enter_pin" to "4-अंकों का सुरक्षा पिन दर्ज करें",
            "unlock_vault" to "तिजोरी अनलॉक करें",
            "biometric_unlock" to "बायोमेट्रिक फिंगरप्रिंट अनलॉक",
            "sync_status" to "सुरक्षित क्लाउड बैकअप",
            "battery_priority" to "बैटरी-अनुकूलित ऑटो सिंक",
            "faces_title" to "ऑफलाइन चेहरा पहचान (Face ID)",
            "faces_desc" to "100% डिवाइस पर ही AI प्रोसेसिंग",
            "on_this_day" to "आज के दिन की यादें",
            "motorola_night" to "मोटोरोला नाइट विज़न",
            "voice_hint" to "आवाज से नेविगेशन के लिए माइक दबाएं",
            "voice_listening" to "सुन रहा है...",
            "voice_commands_avail" to "बोलें: 'तिजोरी खोलो', 'पसंदीदा', 'बैकअप शुरू'",
            "cloud_backup_now" to "एन्क्रिप्टेड बैकअप शुरू करें",
            "high_contrast_active" to "उच्च कंट्रास्ट मोनोक्रोम मोड",
            "ready_for" to "मोटोरोला रेडी फॉर सिंक",
            "storage_breakdown" to "स्टोरेज विश्लेषण",
            "camera_distribution" to "कैमरा सेंसर विवरण",
            "engagement_trends" to "फ़ोटो कैप्चर रुझान",
            "delete" to "हटाएं",
            "share" to "शेयर करें",
            "vault_move" to "तिजोरी में ले जाएं",
            "favorite" to "पसंदीदा",
            "details" to "विवरण",
            "filters" to "फ़िल्टर",
            "close" to "बंद करें",
            "unlock_success" to "तिजोरी अनलॉक हुई",
            "incorrect_pin" to "गलत पिन। पुनः प्रयास करें।",
            "photos_empty" to "कोई फ़ोटो नहीं मिली",
            "scan_faces" to "चेहरे स्कैन करें"
        ),
        AppLanguage.JAPANESE to mapOf(
            "photos" to "写真",
            "albums" to "アルバム",
            "for_you" to "おすすめ",
            "vault" to "保管庫",
            "settings" to "設定",
            "analytics" to "統計",
            "search_hint" to "写真、人物、撮影場所を検索...",
            "all_photos" to "すべての写真",
            "vault_title" to "プライベート保管庫",
            "vault_subtitle" to "AES-256 E2E暗号化 • 完全ローカル保護",
            "enter_pin" to "4桁のPINを入力",
            "unlock_vault" to "保管庫をロック解除",
            "biometric_unlock" to "生体認証ロック解除",
            "sync_status" to "クラウド同期",
            "battery_priority" to "バッテリー優先同期モード",
            "faces_title" to "オフライン顔認識",
            "faces_desc" to "端末内AIで完全オフライン分類",
            "on_this_day" to "過去のこの日",
            "motorola_night" to "モトローラ ナイトビジョン",
            "voice_hint" to "音声操作はマイクをタップ",
            "voice_listening" to "音声認識中...",
            "voice_commands_avail" to "例: '保管庫を開く', 'お気に入り', '同期'",
            "cloud_backup_now" to "暗号化バックアップ開始",
            "high_contrast_active" to "高コントラスト モノクロモード",
            "ready_for" to "Motorola Ready For 連携",
            "storage_breakdown" to "ストレージ分析",
            "camera_distribution" to "カメラセンサー内訳",
            "engagement_trends" to "撮影タイムライン",
            "delete" to "削除",
            "share" to "共有",
            "vault_move" to "保管庫へ移動",
            "favorite" to "お気に入り",
            "details" to "詳細",
            "filters" to "フィルター",
            "close" to "閉じる",
            "unlock_success" to "保管庫を解除しました",
            "incorrect_pin" to "PINが違います。",
            "photos_empty" to "写真が見つかりません",
            "scan_faces" to "オフライン顔再スキャン"
        )
    )

    fun getString(key: String): String {
        return translations[currentLanguage]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }
}

val LocalStrings = compositionLocalOf { LanguageManager }

@Composable
fun tr(key: String): String {
    return LanguageManager.getString(key)
}
